services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: games
        container_name: games-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
              # overriding default php.ini to allow for large form submissions
            - ./docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        networks:
            - games
    nginx:
        image: nginx:1.17-alpine
        container_name: games-nginx
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - games
networks:
    games:
        driver: bridge
